In [6]:
!pip install numpy

In [7]:
import numpy as np

In [ ]:
arr=np.array([1,2,3,4,5,6,7,8,9])

In [ ]:
type(arr)

In [ ]:
#dimension and data type
arr.shape

In [ ]:
print(arr)

In [ ]:
arr.dtype

In [3]:
#Performance metrics

#%timeit [i**3 for i in range(10000)]
%timeit [i*3 for i in range(100000)]

15.2 ms ± 108 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [8]:
#now measuring the performance of the numpy 
%timeit [np.arange(10000)*3]

37.1 µs ± 4.25 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [9]:
#creating numpy array and othe 2d arrays

a=np.array([[1,2,3],[4,5,6],[8,9,10]])

In [10]:
a.shape


(3, 3)

In [12]:
b=np.zeros_like(a)

In [13]:
print(b)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [16]:
np.ones((3,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [18]:
np.ones_like((a),dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [19]:
np.full((2,4),4.3)

array([[4.3, 4.3, 4.3, 4.3],
       [4.3, 4.3, 4.3, 4.3]])

In [20]:
#indexing and slicing
a>5

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [21]:
a[2][2]

10

In [22]:
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 8  9 10]]


In [23]:
a[1:]

array([[ 4,  5,  6],
       [ 8,  9, 10]])

In [27]:
a[1:,2:]

array([[ 6],
       [10]])

In [28]:
print(b)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [29]:
c=a

In [30]:
print(c)

[[ 1  2  3]
 [ 4  5  6]
 [ 8  9 10]]


In [31]:
np.shares_memory(a,c)

True

In [42]:
d=c.copy()

In [43]:
d[0]

array([1, 2, 3])

In [44]:
np.shares_memory(d,c)

False

In [46]:
#random functions 
print(np.random.random())

0.6430221539377797


In [53]:
np.random.randint(1,10)

2

In [57]:
np.random.seed (1001)

In [60]:
print(np.random.randint(10))

9


In [61]:
np.random.randint(1001)

189

In [64]:
np.random.seed (1001)
print(np.random.randint(10))

9


In [65]:
np.random.seed (1001)
print(np.random.randint(10))

9


In [66]:
#random matrix
x=np.random.randint(10,40,size=(3,3))

In [67]:
print(x)

[[39 24 13]
 [22 18 24]
 [37 13 31]]
